# Set repository URL
r <- getOption("repos")
r["CRAN"] <- "https://cloud.r-project.org"
options(repos = r)

# Set lib path
lib_path <- "/packages/"
if (dir.exists(lib_path)) .libPaths(lib_path)

# Install LaTeX environment (for rendering PDFs from RMarkdown, etc.)
pdflatex_ver <- try(system("pdflatex -v", intern = T, wait = T), silent = T)
pdflatex_ver <- grep("^pdfTeX", pdflatex_ver, value = T)
if (!(exists("pdflatex_ver") & length(pdflatex_ver) > 0)) {
  if (!requireNamespace("tinytex", quietly = TRUE)) install.packages("tinytex")
  if (!dir.exists(tinytex::tinytex_root(error = F))) tinytex::install_tinytex()
}

# Load devtools, installing as needed
if (!requireNamespace('devtools', quietly = TRUE)) install.packages('devtools')
library(devtools)

# Install packages
if (!try(packageVersion('httr')) == '1.4.4') 
  install_version('httr', version = '1.4.4', upgrade = FALSE)
if (!try(packageVersion('pkgload')) == '1.3.0') 
  install_version('pkgload', version = '1.3.0', upgrade = FALSE)
if (!try(packageVersion('viridisLite')) == '0.4.0') 
  install_version('viridisLite', version = '0.4.0', upgrade = FALSE)
if (!try(packageVersion('splines')) == '4.1.3') 
  install_version('splines', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('shiny')) == '1.7.2') 
  install_version('shiny', version = '1.7.2', upgrade = FALSE)
if (!try(packageVersion('yaml')) == '2.3.6') 
  install_version('yaml', version = '2.3.6', upgrade = FALSE)
if (!try(packageVersion('remotes')) == '2.4.2') 
  install_version('remotes', version = '2.4.2', upgrade = FALSE)
if (!try(packageVersion('sessioninfo')) == '1.2.2') 
  install_version('sessioninfo', version = '1.2.2', upgrade = FALSE)
if (!try(packageVersion('globals')) == '0.14.0') 
  install_version('globals', version = '0.14.0', upgrade = FALSE)
if (!try(packageVersion('pillar')) == '1.8.1') 
  install_version('pillar', version = '1.8.1', upgrade = FALSE)
if (!try(packageVersion('backports')) == '1.4.1') 
  install_version('backports', version = '1.4.1', upgrade = FALSE)
if (!try(packageVersion('lattice')) == '0.20-45') 
  install_version('lattice', version = '0.20-45', upgrade = FALSE)
if (!try(packageVersion('glue')) == '1.6.2') 
  install_version('glue', version = '1.6.2', upgrade = FALSE)
if (!try(packageVersion('digest')) == '0.6.30') 
  install_version('digest', version = '0.6.30', upgrade = FALSE)
if (!try(packageVersion('promises')) == '1.2.0.1') 
  install_version('promises', version = '1.2.0.1', upgrade = FALSE)
if (!try(packageVersion('rvest')) == '1.0.2') 
  install_version('rvest', version = '1.0.2', upgrade = FALSE)
if (!try(packageVersion('minqa')) == '1.2.5') 
  install_version('minqa', version = '1.2.5', upgrade = FALSE)
if (!try(packageVersion('colorspace')) == '2.0-3') 
  install_version('colorspace', version = '2.0-3', upgrade = FALSE)
if (!try(packageVersion('htmltools')) == '0.5.3') 
  install_version('htmltools', version = '0.5.3', upgrade = FALSE)
if (!try(packageVersion('httpuv')) == '1.6.6') 
  install_version('httpuv', version = '1.6.6', upgrade = FALSE)
if (!try(packageVersion('pkgconfig')) == '2.0.3') 
  install_version('pkgconfig', version = '2.0.3', upgrade = FALSE)
if (!try(packageVersion('broom')) == '0.8.0') 
  install_version('broom', version = '0.8.0', upgrade = FALSE)
if (!try(packageVersion('listenv')) == '0.8.0') 
  install_version('listenv', version = '0.8.0', upgrade = FALSE)
if (!try(packageVersion('xtable')) == '1.8-4') 
  install_version('xtable', version = '1.8-4', upgrade = FALSE)
if (!try(packageVersion('webshot')) == '0.5.3') 
  install_version('webshot', version = '0.5.3', upgrade = FALSE)
if (!try(packageVersion('scales')) == '1.2.0') 
  install_version('scales', version = '1.2.0', upgrade = FALSE)
if (!try(packageVersion('svglite')) == '2.1.0') 
  install_version('svglite', version = '2.1.0', upgrade = FALSE)
if (!try(packageVersion('processx')) == '3.7.0') 
  install_version('processx', version = '3.7.0', upgrade = FALSE)
if (!try(packageVersion('later')) == '1.3.0') 
  install_version('later', version = '1.3.0', upgrade = FALSE)
if (!try(packageVersion('generics')) == '0.1.2') 
  install_version('generics', version = '0.1.2', upgrade = FALSE)
if (!try(packageVersion('ellipsis')) == '0.3.2') 
  install_version('ellipsis', version = '0.3.2', upgrade = FALSE)
if (!try(packageVersion('cachem')) == '1.0.6') 
  install_version('cachem', version = '1.0.6', upgrade = FALSE)
if (!try(packageVersion('pacman')) == '0.5.1') 
  install_version('pacman', version = '0.5.1', upgrade = FALSE)
if (!try(packageVersion('cli')) == '3.4.1') 
  install_version('cli', version = '3.4.1', upgrade = FALSE)
if (!try(packageVersion('magrittr')) == '2.0.3') 
  install_version('magrittr', version = '2.0.3', upgrade = FALSE)
if (!try(packageVersion('crayon')) == '1.5.2') 
  install_version('crayon', version = '1.5.2', upgrade = FALSE)
if (!try(packageVersion('mime')) == '0.12') 
  install_version('mime', version = '0.12', upgrade = FALSE)
if (!try(packageVersion('memoise')) == '2.0.1') 
  install_version('memoise', version = '2.0.1', upgrade = FALSE)
if (!try(packageVersion('evaluate')) == '0.17') 
  install_version('evaluate', version = '0.17', upgrade = FALSE)
if (!try(packageVersion('ps')) == '1.7.1') 
  install_version('ps', version = '1.7.1', upgrade = FALSE)
if (!try(packageVersion('fs')) == '1.5.2') 
  install_version('fs', version = '1.5.2', upgrade = FALSE)
if (!try(packageVersion('fansi')) == '1.0.3') 
  install_version('fansi', version = '1.0.3', upgrade = FALSE)
if (!try(packageVersion('parallelly')) == '1.31.0') 
  install_version('parallelly', version = '1.31.0', upgrade = FALSE)
if (!try(packageVersion('nlme')) == '3.1-160') 
  install_version('nlme', version = '3.1-160', upgrade = FALSE)
if (!try(packageVersion('MASS')) == '7.3-58.1') 
  install_version('MASS', version = '7.3-58.1', upgrade = FALSE)
if (!try(packageVersion('xml2')) == '1.3.3') 
  install_version('xml2', version = '1.3.3', upgrade = FALSE)
if (!try(packageVersion('forcats')) == '0.5.1') 
  install_version('forcats', version = '0.5.1', upgrade = FALSE)
if (!try(packageVersion('pkgbuild')) == '1.3.1') 
  install_version('pkgbuild', version = '1.3.1', upgrade = FALSE)
if (!try(packageVersion('profvis')) == '0.3.7') 
  install_version('profvis', version = '0.3.7', upgrade = FALSE)
if (!try(packageVersion('tools')) == '4.1.3') 
  install_version('tools', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('prettyunits')) == '1.1.1') 
  install_version('prettyunits', version = '1.1.1', upgrade = FALSE)
if (!try(packageVersion('lifecycle')) == '1.0.3') 
  install_version('lifecycle', version = '1.0.3', upgrade = FALSE)
if (!try(packageVersion('stringr')) == '1.4.1') 
  install_version('stringr', version = '1.4.1', upgrade = FALSE)
if (!try(packageVersion('munsell')) == '0.5.0') 
  install_version('munsell', version = '0.5.0', upgrade = FALSE)
if (!try(packageVersion('callr')) == '3.7.2') 
  install_version('callr', version = '3.7.2', upgrade = FALSE)
if (!try(packageVersion('compiler')) == '4.1.3') 
  install_version('compiler', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('systemfonts')) == '1.0.4') 
  install_version('systemfonts', version = '1.0.4', upgrade = FALSE)
if (!try(packageVersion('tinytex')) == '0.42') 
  install_version('tinytex', version = '0.42', upgrade = FALSE)
if (!try(packageVersion('rlang')) == '1.0.6') 
  install_version('rlang', version = '1.0.6', upgrade = FALSE)
if (!try(packageVersion('grid')) == '4.1.3') 
  install_version('grid', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('nloptr')) == '2.0.3') 
  install_version('nloptr', version = '2.0.3', upgrade = FALSE)
if (!try(packageVersion('rstudioapi')) == '0.14') 
  install_version('rstudioapi', version = '0.14', upgrade = FALSE)
if (!try(packageVersion('htmlwidgets')) == '1.5.4') 
  install_version('htmlwidgets', version = '1.5.4', upgrade = FALSE)
if (!try(packageVersion('miniUI')) == '0.1.1.1') 
  install_version('miniUI', version = '0.1.1.1', upgrade = FALSE)
if (!try(packageVersion('rmarkdown')) == '2.17') 
  install_version('rmarkdown', version = '2.17', upgrade = FALSE)
if (!try(packageVersion('boot')) == '1.3-28') 
  install_version('boot', version = '1.3-28', upgrade = FALSE)
if (!try(packageVersion('codetools')) == '0.2-18') 
  install_version('codetools', version = '0.2-18', upgrade = FALSE)
if (!try(packageVersion('R6')) == '2.5.1') 
  install_version('R6', version = '2.5.1', upgrade = FALSE)
if (!try(packageVersion('knitr')) == '1.40') 
  install_version('knitr', version = '1.40', upgrade = FALSE)
if (!try(packageVersion('fastmap')) == '1.1.0') 
  install_version('fastmap', version = '1.1.0', upgrade = FALSE)
if (!try(packageVersion('utf8')) == '1.2.2') 
  install_version('utf8', version = '1.2.2', upgrade = FALSE)
if (!try(packageVersion('stringi')) == '1.7.8') 
  install_version('stringi', version = '1.7.8', upgrade = FALSE)
if (!try(packageVersion('parallel')) == '4.1.3') 
  install_version('parallel', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('Rcpp')) == '1.0.9') 
  install_version('Rcpp', version = '1.0.9', upgrade = FALSE)
if (!try(packageVersion('vctrs')) == '0.4.2') 
  install_version('vctrs', version = '0.4.2', upgrade = FALSE)
if (!try(packageVersion('tidyselect')) == '1.1.2') 
  install_version('tidyselect', version = '1.1.2', upgrade = FALSE)
if (!try(packageVersion('xfun')) == '0.34') 
  install_version('xfun', version = '0.34', upgrade = FALSE)
if (!try(packageVersion('urlchecker')) == '1.0.1') 
  install_version('urlchecker', version = '1.0.1', upgrade = FALSE)
if (!try(packageVersion('kableExtra')) == '1.3.4') 
  install_version('kableExtra', version = '1.3.4', upgrade = FALSE)
if (!try(packageVersion('tictoc')) == '1.0.1') 
  install_version('tictoc', version = '1.0.1', upgrade = FALSE)
if (!try(packageVersion('furrr')) == '0.2.3') 
  install_version('furrr', version = '0.2.3', upgrade = FALSE)
if (!try(packageVersion('future')) == '1.24.0') 
  install_version('future', version = '1.24.0', upgrade = FALSE)
if (!try(packageVersion('purrr')) == '0.3.5') 
  install_version('purrr', version = '0.3.5', upgrade = FALSE)
if (!try(packageVersion('broom.mixed')) == '0.2.9.4') 
  install_version('broom.mixed', version = '0.2.9.4', upgrade = FALSE)
if (!try(packageVersion('lme4')) == '1.1-30') 
  install_version('lme4', version = '1.1-30', upgrade = FALSE)
if (!try(packageVersion('Matrix')) == '1.5-1') 
  install_version('Matrix', version = '1.5-1', upgrade = FALSE)
if (!try(packageVersion('dplyr')) == '1.0.8') 
  install_version('dplyr', version = '1.0.8', upgrade = FALSE)
if (!try(packageVersion('tidyr')) == '1.2.0') 
  install_version('tidyr', version = '1.2.0', upgrade = FALSE)
if (!try(packageVersion('tibble')) == '3.1.8') 
  install_version('tibble', version = '3.1.8', upgrade = FALSE)
if (!try(packageVersion('nycflights13')) == '1.0.2') 
  install_version('nycflights13', version = '1.0.2', upgrade = FALSE)
if (!try(packageVersion('devtools')) == '2.4.5') 
  install_version('devtools', version = '2.4.5', upgrade = FALSE)
if (!try(packageVersion('usethis')) == '2.1.6') 
  install_version('usethis', version = '2.1.6', upgrade = FALSE)
