# Set repository URL
r <- getOption("repos")
r["CRAN"] <- "https://cloud.r-project.org"
options(repos = r)

# Set lib path
lib_path <- "/packages/"
if (dir.exists(lib_path)) .libPaths(lib_path)

# Install LaTeX environment (for rendering PDFs from RMarkdown, etc.)
pdflatex_ver <- try(system("pdflatex -v", intern = T, wait = T), silent = T)
pdflatex_ver <- grep("^pdfTeX", pdflatex_ver, value = T)
if (!(exists("pdflatex_ver") & length(pdflatex_ver) > 0)) {
  if (!requireNamespace("tinytex", quietly = TRUE)) install.packages("tinytex")
  if (!dir.exists(tinytex::tinytex_root(error = F))) tinytex::install_tinytex()
}

# Load devtools, installing as needed
if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")
library(devtools)

# Install packages
if (!try(packageVersion('Rcpp')) == '1.0.9') 
  install_version('Rcpp', version = '1.0.9', upgrade = FALSE)
if (!try(packageVersion('lattice')) == '0.20-45') 
  install_version('lattice', version = '0.20-45', upgrade = FALSE)
if (!try(packageVersion('digest')) == '0.6.29') 
  install_version('digest', version = '0.6.29', upgrade = FALSE)
if (!try(packageVersion('MASS')) == '7.3-58.1') 
  install_version('MASS', version = '7.3-58.1', upgrade = FALSE)
if (!try(packageVersion('grid')) == '4.1.3') 
  install_version('grid', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('nlme')) == '3.1-159') 
  install_version('nlme', version = '3.1-159', upgrade = FALSE)
if (!try(packageVersion('pacman')) == '0.5.1') 
  install_version('pacman', version = '0.5.1', upgrade = FALSE)
if (!try(packageVersion('evaluate')) == '0.17') 
  install_version('evaluate', version = '0.17', upgrade = FALSE)
if (!try(packageVersion('cli')) == '3.4.1') 
  install_version('cli', version = '3.4.1', upgrade = FALSE)
if (!try(packageVersion('rlang')) == '1.0.6') 
  install_version('rlang', version = '1.0.6', upgrade = FALSE)
if (!try(packageVersion('rstudioapi')) == '0.14') 
  install_version('rstudioapi', version = '0.14', upgrade = FALSE)
if (!try(packageVersion('minqa')) == '1.2.4') 
  install_version('minqa', version = '1.2.4', upgrade = FALSE)
if (!try(packageVersion('nloptr')) == '2.0.3') 
  install_version('nloptr', version = '2.0.3', upgrade = FALSE)
if (!try(packageVersion('Matrix')) == '1.5-1') 
  install_version('Matrix', version = '1.5-1', upgrade = FALSE)
if (!try(packageVersion('boot')) == '1.3-28') 
  install_version('boot', version = '1.3-28', upgrade = FALSE)
if (!try(packageVersion('rmarkdown')) == '2.16') 
  install_version('rmarkdown', version = '2.16', upgrade = FALSE)
if (!try(packageVersion('splines')) == '4.1.3') 
  install_version('splines', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('lme4')) == '1.1-30') 
  install_version('lme4', version = '1.1-30', upgrade = FALSE)
if (!try(packageVersion('tools')) == '4.1.3') 
  install_version('tools', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('xfun')) == '0.33') 
  install_version('xfun', version = '0.33', upgrade = FALSE)
if (!try(packageVersion('fastmap')) == '1.1.0') 
  install_version('fastmap', version = '1.1.0', upgrade = FALSE)
if (!try(packageVersion('yaml')) == '2.3.5') 
  install_version('yaml', version = '2.3.5', upgrade = FALSE)
if (!try(packageVersion('compiler')) == '4.1.3') 
  install_version('compiler', version = '4.1.3', upgrade = FALSE)
if (!try(packageVersion('htmltools')) == '0.5.3') 
  install_version('htmltools', version = '0.5.3', upgrade = FALSE)
if (!try(packageVersion('knitr')) == '1.40') 
  install_version('knitr', version = '1.40', upgrade = FALSE)
